### ISSUE TITLE
npx package not working on WSL Ubuntu (linux)

### ISSUE THREAD

**Issue by aaronsantiago** [radically-straightforward/radically-straightforward#10]
The error:
```npx package
(node:106358) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/aaron/workspace/ai_control_panel/odin/node_modules/.bin/package:2
import path from "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2

**Comment by aaronsantiago** [comment]
I've been able to validate that the same problem occur on native Ubuntu across multiple machines.

**Comment by aaronsantiago** [comment]
Comparing the windows and linux versions of the package "binary", the issue seems to with the build or uploading process to npm.

- Renaming `node_modules/.bin/package` to `node_modules/.bin/package.mjs` and running `npx package.mjs` allows package to work properly.
- On Windows, the package binary in .bin is a powershell/batch script that runs `node_modules/package/build/index.mjs`. There does seem to be a bash script in there as well, however:
- On linux, `node_modules/.bin/package` contains the contents of index.mjs itself, which is the primary issue as this file is not loaded as a module.

**Comment by leafac** [comment]
Hi @aaronsantiago,

Thanks for getting in touch.

I tried to reproduce the issue but couldn’t.

I started with the `amd64/ubuntu:latest` Docker image, installed Linuxbrew, then `brew install node` (Node.js v22.2.0). Finally, `npx @radically-straightforward/package` worked fine.

Unfortunately I suppose that the issue has something to do with your setup.

Let me know if you figure it out.
