### ISSUE TITLE
caxa deprecation message on npm is not straightforward

### ISSUE THREAD

**Issue by aminya** [radically-straightforward/radically-straightforward#12]
On npm, the deprecation message says contact npm, although this is a user package.

```
Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

https://www.npmjs.com/package/caxa

What's the actual migration guide?

**Comment by leafac** [comment]
Hi @aminya,

Thanks for reaching out.

That message was set by npmjs.com when I deprecated the package via the web interface and I can’t change it.

The successor of caxa is https://github.com/radically-straightforward/radically-straightforward/tree/main/package

Let me know how it works for you.
