### ISSUE TITLE
Skip dependency deduplication in package

### ISSUE THREAD

**Issue by aminya** [radically-straightforward/radically-straightforward#13]
I am trying to migrate from `caxa` to `package`, however, the CLI tool fails with the following message. It's because `package` assumes I am using `npm` as my package manager although I am using pnpm. Is there a way to skip this step? I don't want package to do any special changes to my node_modules. I have already bundled my application in the `dist` folder. 

```js
node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: npm dedupe
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm error A complete log of this run can be found in: /home/aminya/.npm/_logs/2024-10-12T07_54_13_458Z-debug-0.log

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:421:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm dedupe',
  stdout: '',
  stderr: 'npm error code EUNSUPPORTEDPROTOCOL\n' +
    'npm error Unsupported URL Type "workspace:": workspace:*\n' +
    'npm error A complete log of this run can be found in: /home/aminya/.npm/_logs/2024-10-12T07_54_13_458Z-debug-0.log\n'
}

```

**Comment by leafac** [comment]
There isn’t a way to skip this step, and I think it should remain this way, because `package` is designed around the way `npm` does things. I never tried it with another package manager, and things may or may not work. In particular, `package` expects to find `node_modules/` in a certain way, `node_modules/.bin/` in a certain way, `package.json` in a certain place, and so forth.
