### ISSUE TITLE
Support specifying the executable entry for package

### ISSUE THREAD

**Issue by aminya** [radically-straightforward/radically-straightforward#14]
`package` assumes that the entry file for the executable is `build/index.mjs`, which is not the same for all the use cases.

**Comment by leafac** [comment]
Hi @aminya,

Thanks for reaching out.

The idea behind this design decision is that, if necessary, you may put a script at `build/index.mjs` that starts the application. It keeps things simple on our end, and allows you to specify how to run your application using JavaScript, which gives you more flexibility than command-line options or something like that could.

Do you have an use case that can’t work like that?

**Comment by aminya** [comment]
Yes, the target file of my package has the same name as my package, and it's under `dist`, not `build`. Also, I don't use `mjs` extensions. My binaries are supposed to run on old Nodejs without ESM support.  I suggest at least documenting these if you intend to keep the package strict. There are too many undocumented assumptions here.

**Comment by leafac** [comment]
Fair point. As I’m documenting things around here better I’ll make sure to mention that generally we support and test with the latest version of dependencies (in this case, the dependency is Node.js itself), and that we use the latest features (in this case, ESM).
