### ISSUE TITLE
Follow up on https://github.com/leafac/caxa/issues/21

### ISSUE THREAD

**Issue by leafac** [radically-straightforward/radically-straightforward#2]
> @leafac Could I ask you why you never add commit messages on your repos?

@robertsLando: In projects in which I’m one of the only developers I don’t consider it worth it to rebase and make the commit history neat. I do that when I’m contributing to bigger projects with lots of maintaners, in which the Git history is more useful.

**Comment by robertsLando** [comment]
@leafac I understand but I think this makes difficult for other users to help you, I personally always check commits messages when a new version comes to understand what changed and also what each commit specifically changed so I don't agree with your choice but I respect it 🙏🏼

**Comment by leafac** [comment]
Yeah, that’s a fair point 😅 You’re very diligent 👏

At some point, as the projects mature, I’ll start neating up the Git history. In the meanwhile, hopefully the CHANGELOG helps? 😬

**Comment by robertsLando** [comment]
@leafac sure, better then nothing :)
