### ISSUE TITLE
No single click usage

### ISSUE THREAD

**Issue by jowparks** [radically-straightforward/radically-straightforward#3]
This repository is not a great drop in replacement for caxa, let me describe the use case:

We have semi technical users for our cryptocurrency, they run cheap VPSs to run our node software, or on native windows. We want them to be able to download a single file and run it. With this implementation, they would need to download, extract, change directory, and then run.

It seems to me a major utility of caxa was removed upon creation of this package. Thoughts?

**Comment by leafac** [comment]
Hey @jowparks,

Thanks for looking into my new project and providing feedback so quickly 🤗

In macOS and Linux if you simply download an executable from the internet it doesn’t come with the permissions necessary to execute it—you must `chmod a+x example-application` first. Most applications solve this issue by distributing a tarball, which preserves the permissions of executables upon extraction, but this defeats the point of the self-extracting executable produced by `caxa` in the first place.

In the end, your users either have to extract a compressed file or change file permissions.

With Radically Straightforward · Package the deployment story is still a three-step process:

```console
$ curl -O https://example.com/package.tar.gz
$ tar -xzf package.tar.gz
$ ./package/package
```

> **Note:** The latest versions of Windows come with `curl` and `tar`, and despite the name `tar` can work `.zip` files. So the instructions are cross-platform—you just have to adapt the name of the `package.tar.gz`.

What do you think?

**Comment by jowparks** [comment]
I think that makes sense, I had forgotten about file permissions step. I still have two concerns for unskilled users:

1. portability of executable: You cannot simply move the executable to a new folder anymore, the entire folder must be moved.
2. Folder abstraction layer: the user now has to reason about the file system relative to the executable. Before the executable was the project entirely.


Let’s use an example of a user downloading an app. They curl/whet the app, untar, and use it. Later they want to move the app, they then go to the folder and see the executable they were running and move it, the executable then fails to work.


I think it is for these reasons projects like pkg bundle into an single binary.

thanks for the quick response!

**Comment by leafac** [comment]
You’re right. That’s the tradeoff:

- caxa was better than Radically Straightforward · Package in that caxa produced a neat binary that was a single file, with all the advantages you mentioned.

- caxa and Radically Straightforward · Package tie in that both require one extra step between downloading and running. Either that extra step is extracting a compressed file, or changing file permissions.

- Radically Straightforward · Package is better than caxa in that it’s much simpler conceptually, it doesn’t run into issues with anti-virus software, it doesn’t run into issues with temporary filesystems deleting files arbitrarily, it doesn’t incur a performance penalty on the first run every boot while it’s extracting the package again, it doesn’t clutter the filesystem as you deploy new versions of the application until the disk fills up and a server restart is necessary, and so forth.

After pondering about all this for a couple years of using caxa, I think that Radically Straightforward · Package is the winner 🤗

> thanks for the quick response!

Well, thank you for the conversation. I’m flattered that you’re interested in my project 🤗

**Comment by bradisbell** [comment]
Frankly, the self-extracting executable was the whole reason to use a tool such as caxa.  Lowering friction for users was worth it, even if it were to take 10 seconds to start.  The tradeoffs you have chosen may make sense for you and your users, but they do not for any use case I work in.  Unfortunately, we'll have to find another tool.

**Comment by leafac** [comment]
Hi @bradisbell,

I’m happy to read that caxa satisfied your use case so well! 😃

As far as I can tell there isn’t any other tool quite like it. Would you be interested in picking it up? I’d be happy to see caxa’s original vision live on, even though I prefer Radically Straightforward · Package moving forward.

If you’re interested, please reach out to me at caxa@leafac.com. We can talk to make sure that you understand how caxa works, discuss the directions in which you could take it, and so forth.

**Comment by leafac** [comment]
I’m closing the issue for now. If you feel like there’s more that you want to say we can reopen it 🤗
