### ISSUE TITLE
A README for the main repo root and add project description to the github repo?

### ISSUE THREAD

**Issue by daluu** [radically-straightforward/radically-straightforward#4]
I found a README under the package directory, and see from referenced issue, this supersedes caxa. However, to a newcoming just visiting the new repo, there is nothing to tell about what is repo is about. Rather than force user to navigate to code like package directory to find more info in a README there, it may be good to have a top level README to give some summary about this repo, if not all the detailed instructions that you'd find in the one under package directory.

There's also no project description in the github repo.

**Comment by leafac** [comment]
I’m working on briging some other projects under the Radically Straightforward umbrella and writing the documentation. It’ll be great! 🤗

**Comment by leafac** [comment]
I’m closing the issue for now as I’m working on the documentation 🤗
