### ISSUE TITLE
Add README and docs - What is this?

### ISSUE THREAD

**Issue by benbucksch** [radically-straightforward/radically-straightforward#7]
Hey @leafac , I see that you pointed @leafac/sqlite here. But I don't know what "this" is. What is the objective of the software in this repository? It contains very different things, like an sqlite library, a server for something (but I'm not clear for what), it has "caddy", but I don't know what it is. (At least "package", despite the generic name, has a little explanation for what it does.)

* The name says nothing about the objective.
* The README.md is empty
* There is a "documentation/" folder, but it contains no documentation (other than the auto-generated docs from upstream libs).
* There are no commit messages at all. Like, none. (See #2) I've never seen a commit history being completely empty.

Another visitor had the exact same problem in #4. That is closed now, but the problem is not solved.

**Comment by benbucksch** [comment]
The reason why I ask is: I was planning to use your sqlite library, because your ideas are great.

**Comment by leafac** [comment]
@benbucksch: You may find the documentation for `@radically-straightforward/sqlite` at https://github.com/radically-straightforward/radically-straightforward/tree/main/sqlite (see the README). Also, the source code is documented, so you’ll also see documentation in your editor as you hover over function names. If there’s something in the documentation that’s unclear, please reach out and we’ll make it better.

---

`@radically-straightforward/package` packages a Node.js application for distribution, for example, if you want install a Node.js application on your servers, or distribute an open-source application (see, for example, https://github.com/courselore/courselore, which inspired the creation of all the tools you’ll find here).

Like, `@radically-straightforward/sqlite`, `@radically-straightforward/package` is also documented—in this case at https://github.com/radically-straightforward/radically-straightforward/tree/main/package.

---

`@radically-straightforward/documentation` is a tool that generates READMEs from TypeScript source code. It’s documented at https://github.com/radically-straightforward/radically-straightforward/tree/main/documentation.

---

Finally, **Radically Straightforward** itself is an umbrella for a set of tools that fill gaps in Node.js’s ecosystem, from tagged templates for better-sqlite3, to installing https://caddyserver.com/ as a reverse proxy, and so forth.

I’m now working on the `server` package. Every other package here is already documented.

And when I finish that, I’ll document the top level of **Radically Straightforward** itself.
