### ISSUE TITLE
Clarify suggested usage pattern for package

### ISSUE THREAD

**Issue by aaronsantiago** [radically-straightforward/radically-straightforward#9]
Currently when using package as noted in the README there are a couple odd behaviors that make it unclear how package is supposed to _actually_ be used.

- Package removes package itself from node_modules, requiring a new `npm install` before each build
- npx also defaults to the instance of node that is now placed into `node_modules/.bin`, causing package to throw an error on subsequent builds. Deleting `node_modules/bin` solves this

It feels like the way that package wants to be used is to copy the entire project (including node_modules and package.json) into a new directory and build from there, but that's not made clear in the readme--and is also quite laborious to do manually. An example package.json entry that does this copying and removing would go a long way without adding any complexity to package.

**Comment by leafac** [comment]
Hi @aaronsantiago,

Thanks for reaching out.

I added the following note to the documentation. I hope that addresses your concern.

> **Note:** Running this command has some side-effects, for example, removing development dependencies and copying the Node.js executable into `node_modules/.bin/`. This tool has been designed to [run in a build server, for example, GitHub Actions](https://github.com/leafac/kill-the-newsletter/blob/33fda2645c79d81856ef9c9d47ae246df33e5f8f/.github/workflows/main.yml#L19). If you run it locally, then you may want to copy the project directory to a different location and run `npx package` on the copy.
